name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'  # Or 'temurin', depending on your project requirements
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Install dependencies and run tests
        run: mvn -B clean install

      - name: Upload test results
        if: always()  # Ensures the step runs even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
      - name: Generate Javadoc
        run: mvn javadoc:javadoc # Default location for Maven Surefire Plugin test reports
      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs/javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
